### ISSUE TITLE
fix: modal dark mode 🌑🌖

### ISSUE THREAD

**Issue by wflore19** [wflore19/CampusConnect#26]
### Description

Modal has tailwindcss styles instead of using Radix Themes components
![image](https://github.com/user-attachments/assets/e8038aed-b253-4855-97df-dbbe9041c26c)

### Acceptance Criteria

- Replace tailwindcss styles with Radix Components

### Additional Context

Similar to the `dashboard.tsx` component

**Comment by DachiCharkviani** [comment]
Hello, I am a first time contributor and would like to work on this issue!

**Comment by wflore19** [comment]
Hey! @DachiCharkviani would love to have you contribute, unfortunately I just solved this issue in the past hour before I saw this message, feel free to comment on any other open issues and i'll be adding more later!

**Comment by wflore19** [comment]
Solved ada490c0f9ddf17a42aa175aeb9e0fb4ac41e900

**Comment by DachiCharkviani** [comment]
> Hey! @DachiCharkviani would love to have you contribute, unfortunately I just solved this issue in the past hour before I saw this message, feel free to comment on any other open issues and i'll be adding more later!

Thanks for letting me know!

I also commented on one of your other issues! If that one is still relevant could you please confirm the assignment there via comment reply?
